// Shared Tailwind Play-CDN config for the Obsidian Infrastructure design system.
// Loaded on every page right after https://cdn.tailwindcss.com.
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#e2e2eb",
        "on-secondary-fixed-variant": "#004f53",
        "on-secondary-fixed": "#002022",
        "on-tertiary-fixed-variant": "#4f319c",
        "on-surface-variant": "#cec2d6",
        "tertiary-fixed-dim": "#cebdff",
        "surface-dim": "#111319",
        "error": "#ffb4ab",
        "outline-variant": "#4c4354",
        "on-tertiary-container": "#d7c8ff",
        "on-secondary-container": "#006a6f",
        "primary-fixed": "#efdbff",
        "tertiary-fixed": "#e8ddff",
        "background": "#111319",
        "primary-container": "#7928ca",
        "inverse-primary": "#7f30d0",
        "on-secondary": "#00373a",
        "on-primary": "#470083",
        "inverse-surface": "#e2e2eb",
        "primary-fixed-dim": "#dbb8ff",
        "tertiary-container": "#6145af",
        "secondary-container": "#00f1fd",
        "on-primary-fixed": "#2b0052",
        "inverse-on-surface": "#2e3037",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "outline": "#988d9f",
        "surface-container-lowest": "#0c0e14",
        "secondary": "#dcfdff",
        "on-error": "#690005",
        "on-tertiary-fixed": "#21005e",
        "on-primary-fixed-variant": "#6600b7",
        "surface": "#111319",
        "on-primary-container": "#e1c4ff",
        "surface-container": "#1e1f26",
        "tertiary": "#cebdff",
        "surface-variant": "#33343b",
        "on-tertiary": "#381385",
        "on-surface": "#e2e2eb",
        "surface-bright": "#373940",
        "secondary-fixed": "#6ff6ff",
        "surface-container-high": "#282a30",
        "surface-container-low": "#191b22",
        "primary": "#dbb8ff",
        "surface-tint": "#dbb8ff",
        "surface-container-highest": "#33343b",
        "secondary-fixed-dim": "#00dce6"
      },
      borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", full: "9999px" },
      spacing: {
        "margin-mobile": "1.25rem",
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-2xl": "4rem",
        "space-md": "1rem",
        "gutter": "1.5rem",
        "margin": "3rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem"
      },
      fontFamily: {
        "body-sm": ["Manrope"],
        "headline-sm": ["Hanken Grotesk"],
        "code-inline": ["JetBrains Mono"],
        "label-code": ["JetBrains Mono"],
        "body-md": ["Manrope"],
        "headline-md": ["Hanken Grotesk"],
        "display-hero": ["Hanken Grotesk"],
        "body-lg": ["Manrope"],
        "display-hero-mobile": ["Hanken Grotesk"],
        "label-caps": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"]
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "600" }],
        "code-inline": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-code": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "30px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "600" }]
      }
    }
  }
};
